/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 71
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 8
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 22
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__word = 1,
  sym__newline = 2,
  sym_comment = 3,
  anon_sym_EQ = 4,
  sym_string = 5,
  aux_sym_number_token1 = 6,
  aux_sym_number_token2 = 7,
  sym_boolean = 8,
  anon_sym_include = 9,
  anon_sym_include_if_exists = 10,
  anon_sym_include_dir = 11,
  aux_sym_include_token1 = 12,
  anon_sym_local = 13,
  anon_sym_host = 14,
  anon_sym_hostssl = 15,
  anon_sym_hostnossl = 16,
  anon_sym_hostgssenc = 17,
  anon_sym_hostnogssenc = 18,
  anon_sym_COMMA = 19,
  aux_sym__hba_name_token1 = 20,
  anon_sym_PLUS = 21,
  anon_sym_AT = 22,
  aux_sym_file_reference_token1 = 23,
  sym_regex = 24,
  sym_quoted_name = 25,
  sym_ip_address = 26,
  aux_sym_auth_option_token1 = 27,
  sym_backreference = 28,
  sym_source_file = 29,
  sym__entry = 30,
  sym_setting = 31,
  sym__value = 32,
  sym_number = 33,
  sym_include = 34,
  sym_hba_rule = 35,
  sym_database = 36,
  sym_user = 37,
  sym__hba_name = 38,
  sym_role_group = 39,
  sym_file_reference = 40,
  sym_address = 41,
  sym_auth_method = 42,
  sym_auth_option = 43,
  sym_user_mapping = 44,
  aux_sym_source_file_repeat1 = 45,
  aux_sym_hba_rule_repeat1 = 46,
  aux_sym_database_repeat1 = 47,
  alias_sym_bare_value = 48,
  alias_sym_database_user = 49,
  alias_sym_hostname = 50,
  alias_sym_map_name = 51,
  alias_sym_netmask = 52,
  alias_sym_option_name = 53,
  alias_sym_setting_name = 54,
  alias_sym_system_user = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__word] = "_word",
  [sym__newline] = "_newline",
  [sym_comment] = "comment",
  [anon_sym_EQ] = "=",
  [sym_string] = "string",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "unit",
  [sym_boolean] = "boolean",
  [anon_sym_include] = "include",
  [anon_sym_include_if_exists] = "include_if_exists",
  [anon_sym_include_dir] = "include_dir",
  [aux_sym_include_token1] = "path",
  [anon_sym_local] = "connection_type",
  [anon_sym_host] = "connection_type",
  [anon_sym_hostssl] = "connection_type",
  [anon_sym_hostnossl] = "connection_type",
  [anon_sym_hostgssenc] = "connection_type",
  [anon_sym_hostnogssenc] = "connection_type",
  [anon_sym_COMMA] = ",",
  [aux_sym__hba_name_token1] = "name",
  [anon_sym_PLUS] = "+",
  [anon_sym_AT] = "@",
  [aux_sym_file_reference_token1] = "path",
  [sym_regex] = "regex",
  [sym_quoted_name] = "quoted_name",
  [sym_ip_address] = "ip_address",
  [aux_sym_auth_option_token1] = "option_value",
  [sym_backreference] = "backreference",
  [sym_source_file] = "source_file",
  [sym__entry] = "_entry",
  [sym_setting] = "setting",
  [sym__value] = "_value",
  [sym_number] = "number",
  [sym_include] = "include",
  [sym_hba_rule] = "hba_rule",
  [sym_database] = "database",
  [sym_user] = "user",
  [sym__hba_name] = "_hba_name",
  [sym_role_group] = "role_group",
  [sym_file_reference] = "file_reference",
  [sym_address] = "address",
  [sym_auth_method] = "auth_method",
  [sym_auth_option] = "auth_option",
  [sym_user_mapping] = "user_mapping",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_hba_rule_repeat1] = "hba_rule_repeat1",
  [aux_sym_database_repeat1] = "database_repeat1",
  [alias_sym_bare_value] = "bare_value",
  [alias_sym_database_user] = "database_user",
  [alias_sym_hostname] = "hostname",
  [alias_sym_map_name] = "map_name",
  [alias_sym_netmask] = "netmask",
  [alias_sym_option_name] = "option_name",
  [alias_sym_setting_name] = "setting_name",
  [alias_sym_system_user] = "system_user",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__word] = sym__word,
  [sym__newline] = sym__newline,
  [sym_comment] = sym_comment,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_string] = sym_string,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [sym_boolean] = sym_boolean,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_include_if_exists] = anon_sym_include_if_exists,
  [anon_sym_include_dir] = anon_sym_include_dir,
  [aux_sym_include_token1] = aux_sym_include_token1,
  [anon_sym_local] = anon_sym_local,
  [anon_sym_host] = anon_sym_local,
  [anon_sym_hostssl] = anon_sym_local,
  [anon_sym_hostnossl] = anon_sym_local,
  [anon_sym_hostgssenc] = anon_sym_local,
  [anon_sym_hostnogssenc] = anon_sym_local,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym__hba_name_token1] = aux_sym__hba_name_token1,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_file_reference_token1] = aux_sym_include_token1,
  [sym_regex] = sym_regex,
  [sym_quoted_name] = sym_quoted_name,
  [sym_ip_address] = sym_ip_address,
  [aux_sym_auth_option_token1] = aux_sym_auth_option_token1,
  [sym_backreference] = sym_backreference,
  [sym_source_file] = sym_source_file,
  [sym__entry] = sym__entry,
  [sym_setting] = sym_setting,
  [sym__value] = sym__value,
  [sym_number] = sym_number,
  [sym_include] = sym_include,
  [sym_hba_rule] = sym_hba_rule,
  [sym_database] = sym_database,
  [sym_user] = sym_user,
  [sym__hba_name] = sym__hba_name,
  [sym_role_group] = sym_role_group,
  [sym_file_reference] = sym_file_reference,
  [sym_address] = sym_address,
  [sym_auth_method] = sym_auth_method,
  [sym_auth_option] = sym_auth_option,
  [sym_user_mapping] = sym_user_mapping,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_hba_rule_repeat1] = aux_sym_hba_rule_repeat1,
  [aux_sym_database_repeat1] = aux_sym_database_repeat1,
  [alias_sym_bare_value] = alias_sym_bare_value,
  [alias_sym_database_user] = alias_sym_database_user,
  [alias_sym_hostname] = alias_sym_hostname,
  [alias_sym_map_name] = alias_sym_map_name,
  [alias_sym_netmask] = alias_sym_netmask,
  [alias_sym_option_name] = alias_sym_option_name,
  [alias_sym_setting_name] = alias_sym_setting_name,
  [alias_sym_system_user] = alias_sym_system_user,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__word] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_include_if_exists] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_include_dir] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_include_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_local] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_host] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_hostssl] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_hostnossl] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_hostgssenc] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_hostnogssenc] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__hba_name_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_file_reference_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_regex] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_name] = {
    .visible = true,
    .named = true,
  },
  [sym_ip_address] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_auth_option_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_backreference] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__entry] = {
    .visible = false,
    .named = true,
  },
  [sym_setting] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_include] = {
    .visible = true,
    .named = true,
  },
  [sym_hba_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_database] = {
    .visible = true,
    .named = true,
  },
  [sym_user] = {
    .visible = true,
    .named = true,
  },
  [sym__hba_name] = {
    .visible = false,
    .named = true,
  },
  [sym_role_group] = {
    .visible = true,
    .named = true,
  },
  [sym_file_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_address] = {
    .visible = true,
    .named = true,
  },
  [sym_auth_method] = {
    .visible = true,
    .named = true,
  },
  [sym_auth_option] = {
    .visible = true,
    .named = true,
  },
  [sym_user_mapping] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_hba_rule_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_database_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_bare_value] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_database_user] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_hostname] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_map_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_netmask] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_option_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_setting_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_system_user] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_address = 1,
  field_database = 2,
  field_database_user = 3,
  field_map = 4,
  field_method = 5,
  field_name = 6,
  field_netmask = 7,
  field_option = 8,
  field_path = 9,
  field_system_user = 10,
  field_type = 11,
  field_user = 12,
  field_value = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_address] = "address",
  [field_database] = "database",
  [field_database_user] = "database_user",
  [field_map] = "map",
  [field_method] = "method",
  [field_name] = "name",
  [field_netmask] = "netmask",
  [field_option] = "option",
  [field_path] = "path",
  [field_system_user] = "system_user",
  [field_type] = "type",
  [field_user] = "user",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 2},
  [3] = {.index = 2, .length = 1},
  [5] = {.index = 3, .length = 3},
  [6] = {.index = 3, .length = 3},
  [7] = {.index = 6, .length = 2},
  [8] = {.index = 3, .length = 3},
  [9] = {.index = 3, .length = 3},
  [10] = {.index = 8, .length = 1},
  [12] = {.index = 9, .length = 4},
  [14] = {.index = 13, .length = 1},
  [15] = {.index = 14, .length = 5},
  [16] = {.index = 19, .length = 5},
  [17] = {.index = 24, .length = 2},
  [18] = {.index = 26, .length = 6},
  [19] = {.index = 32, .length = 6},
  [20] = {.index = 6, .length = 2},
  [21] = {.index = 38, .length = 7},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_value, 1},
  [2] =
    {field_path, 1},
  [3] =
    {field_database_user, 2},
    {field_map, 0},
    {field_system_user, 1},
  [6] =
    {field_name, 0},
    {field_value, 2},
  [8] =
    {field_path, 2},
  [9] =
    {field_database, 1},
    {field_method, 3},
    {field_type, 0},
    {field_user, 2},
  [13] =
    {field_option, 0},
  [14] =
    {field_database, 1},
    {field_method, 3},
    {field_option, 4, .inherited = true},
    {field_type, 0},
    {field_user, 2},
  [19] =
    {field_address, 3},
    {field_database, 1},
    {field_method, 4},
    {field_type, 0},
    {field_user, 2},
  [24] =
    {field_option, 0, .inherited = true},
    {field_option, 1, .inherited = true},
  [26] =
    {field_address, 3},
    {field_database, 1},
    {field_method, 5},
    {field_netmask, 4},
    {field_type, 0},
    {field_user, 2},
  [32] =
    {field_address, 3},
    {field_database, 1},
    {field_method, 4},
    {field_option, 5, .inherited = true},
    {field_type, 0},
    {field_user, 2},
  [38] =
    {field_address, 3},
    {field_database, 1},
    {field_method, 5},
    {field_netmask, 4},
    {field_option, 6, .inherited = true},
    {field_type, 0},
    {field_user, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_bare_value,
  },
  [2] = {
    [0] = alias_sym_setting_name,
  },
  [4] = {
    [0] = aux_sym__hba_name_token1,
  },
  [5] = {
    [0] = alias_sym_map_name,
    [1] = alias_sym_system_user,
    [2] = alias_sym_database_user,
  },
  [6] = {
    [0] = alias_sym_map_name,
    [1] = alias_sym_system_user,
  },
  [7] = {
    [0] = alias_sym_setting_name,
  },
  [8] = {
    [0] = alias_sym_map_name,
    [2] = alias_sym_database_user,
  },
  [9] = {
    [0] = alias_sym_map_name,
  },
  [11] = {
    [1] = aux_sym__hba_name_token1,
  },
  [13] = {
    [0] = alias_sym_hostname,
  },
  [18] = {
    [4] = alias_sym_netmask,
  },
  [20] = {
    [0] = alias_sym_option_name,
  },
  [21] = {
    [4] = alias_sym_netmask,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 14,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 17,
  [35] = 30,
  [36] = 36,
  [37] = 37,
  [38] = 32,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 15,
  [44] = 16,
  [45] = 18,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 67,
  [70] = 68,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '\n', 33,
        '\r', 1,
        '"', 4,
        '#', 34,
        '\'', 47,
        '+', 49,
        ',', 46,
        '-', 21,
        '/', 52,
        '=', 38,
        '@', 50,
        '\\', 22,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(33);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '\'') ADVANCE(48);
      if (lookahead == '+') ADVANCE(49);
      if (lookahead == ',') ADVANCE(46);
      if (lookahead == '/') ADVANCE(52);
      if (lookahead == '@') ADVANCE(50);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(62);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead == '=') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(5);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(45);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == ',') ADVANCE(46);
      if (lookahead == ':') ADVANCE(59);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 8:
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ',') ADVANCE(51);
      END_STATE();
    case 9:
      if (lookahead == '\'') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == ':') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == ':') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == ':') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == '.') ADVANCE(27);
      END_STATE();
    case 14:
      if (lookahead == '.') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == '.') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 16:
      if (lookahead == '.') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == ':') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 20:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 29:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '\n', 33,
        '\r', 1,
        '"', 4,
        '#', 34,
        '\'', 9,
        '-', 21,
        '/', 52,
        '=', 38,
        '\\', 22,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 30:
      if (eof) ADVANCE(32);
      if (lookahead == '\n') ADVANCE(33);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(30);
      END_STATE();
    case 31:
      if (eof) ADVANCE(32);
      if (lookahead == '\n') ADVANCE(33);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == ':') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != '=') ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__word);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != '=') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__word);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != '=') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '\'') ADVANCE(47);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != '=') ADVANCE(48);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '\'') ADVANCE(9);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_include_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym__hba_name_token1);
      if (lookahead == '\'') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == '#' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym__hba_name_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != '=') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_file_reference_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ',') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_regex);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ',') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_quoted_name);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_ip_address);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_ip_address);
      if (lookahead == '/') ADVANCE(36);
      if (('.' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_ip_address);
      if (lookahead == '/') ADVANCE(25);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_ip_address);
      if (lookahead == '/') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_ip_address);
      if (lookahead == '/') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_ip_address);
      if (lookahead == '/') ADVANCE(25);
      if (('.' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_ip_address);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_ip_address);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_auth_option_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_backreference);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'h') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(2);
      if (lookahead == 'l') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(4);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(5);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(6);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(7);
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 6:
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(14);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 8:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_boolean);
      END_STATE();
    case 14:
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(13);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 20:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_host);
      if (lookahead == 'g') ADVANCE(26);
      if (lookahead == 'n') ADVANCE(27);
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 25:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 29:
      if (lookahead == 'd') ADVANCE(34);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_local);
      END_STATE();
    case 31:
      if (lookahead == 's') ADVANCE(35);
      END_STATE();
    case 32:
      if (lookahead == 'g') ADVANCE(36);
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(38);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 36:
      if (lookahead == 's') ADVANCE(41);
      END_STATE();
    case 37:
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_hostssl);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_include);
      if (lookahead == '_') ADVANCE(43);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 41:
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 42:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 43:
      if (lookahead == 'd') ADVANCE(47);
      if (lookahead == 'i') ADVANCE(48);
      END_STATE();
    case 44:
      if (lookahead == 'c') ADVANCE(49);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_hostnossl);
      END_STATE();
    case 47:
      if (lookahead == 'i') ADVANCE(51);
      END_STATE();
    case 48:
      if (lookahead == 'f') ADVANCE(52);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_hostgssenc);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(53);
      END_STATE();
    case 51:
      if (lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 52:
      if (lookahead == '_') ADVANCE(55);
      END_STATE();
    case 53:
      if (lookahead == 'c') ADVANCE(56);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_include_dir);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_hostnogssenc);
      END_STATE();
    case 57:
      if (lookahead == 'x') ADVANCE(58);
      END_STATE();
    case 58:
      if (lookahead == 'i') ADVANCE(59);
      END_STATE();
    case 59:
      if (lookahead == 's') ADVANCE(60);
      END_STATE();
    case 60:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 61:
      if (lookahead == 's') ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_include_if_exists);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 29},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 29},
  [20] = {.lex_state = 29},
  [21] = {.lex_state = 29},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 29},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 31},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 6},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 6},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 8},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__word] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_include_if_exists] = ACTIONS(1),
    [anon_sym_include_dir] = ACTIONS(1),
    [anon_sym_local] = ACTIONS(1),
    [anon_sym_host] = ACTIONS(1),
    [anon_sym_hostssl] = ACTIONS(1),
    [anon_sym_hostnossl] = ACTIONS(1),
    [anon_sym_hostgssenc] = ACTIONS(1),
    [anon_sym_hostnogssenc] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym__hba_name_token1] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_regex] = ACTIONS(1),
    [sym_quoted_name] = ACTIONS(1),
    [sym_backreference] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(66),
    [sym__entry] = STATE(60),
    [sym_setting] = STATE(60),
    [sym_include] = STATE(60),
    [sym_hba_rule] = STATE(60),
    [sym_user_mapping] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym__word] = ACTIONS(7),
    [sym__newline] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_include] = ACTIONS(11),
    [anon_sym_include_if_exists] = ACTIONS(11),
    [anon_sym_include_dir] = ACTIONS(11),
    [anon_sym_local] = ACTIONS(13),
    [anon_sym_host] = ACTIONS(15),
    [anon_sym_hostssl] = ACTIONS(15),
    [anon_sym_hostnossl] = ACTIONS(15),
    [anon_sym_hostgssenc] = ACTIONS(15),
    [anon_sym_hostnogssenc] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__word,
    ACTIONS(13), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym__newline,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(11), 3,
      anon_sym_include,
      anon_sym_include_if_exists,
      anon_sym_include_dir,
    ACTIONS(15), 5,
      anon_sym_host,
      anon_sym_hostssl,
      anon_sym_hostnossl,
      anon_sym_hostgssenc,
      anon_sym_hostnogssenc,
    STATE(46), 5,
      sym__entry,
      sym_setting,
      sym_include,
      sym_hba_rule,
      sym_user_mapping,
  [38] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym__word,
    ACTIONS(26), 1,
      sym__newline,
    ACTIONS(32), 1,
      anon_sym_local,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(29), 3,
      anon_sym_include,
      anon_sym_include_if_exists,
      anon_sym_include_dir,
    ACTIONS(35), 5,
      anon_sym_host,
      anon_sym_hostssl,
      anon_sym_hostnossl,
      anon_sym_hostgssenc,
      anon_sym_hostnogssenc,
    STATE(65), 5,
      sym__entry,
      sym_setting,
      sym_include,
      sym_hba_rule,
      sym_user_mapping,
  [76] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      sym__newline,
    ACTIONS(38), 10,
      sym__word,
      anon_sym_include,
      anon_sym_include_if_exists,
      anon_sym_include_dir,
      anon_sym_local,
      anon_sym_host,
      anon_sym_hostssl,
      anon_sym_hostnossl,
      anon_sym_hostgssenc,
      anon_sym_hostnogssenc,
  [96] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_PLUS,
    ACTIONS(44), 1,
      anon_sym_AT,
    STATE(8), 1,
      sym_database,
    ACTIONS(40), 2,
      sym__word,
      aux_sym__hba_name_token1,
    ACTIONS(46), 2,
      sym_regex,
      sym_quoted_name,
    STATE(12), 3,
      sym__hba_name,
      sym_role_group,
      sym_file_reference,
  [122] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_PLUS,
    ACTIONS(44), 1,
      anon_sym_AT,
    STATE(7), 1,
      sym_database,
    ACTIONS(40), 2,
      sym__word,
      aux_sym__hba_name_token1,
    ACTIONS(46), 2,
      sym_regex,
      sym_quoted_name,
    STATE(12), 3,
      sym__hba_name,
      sym_role_group,
      sym_file_reference,
  [148] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_PLUS,
    ACTIONS(44), 1,
      anon_sym_AT,
    STATE(49), 1,
      sym_user,
    ACTIONS(40), 2,
      sym__word,
      aux_sym__hba_name_token1,
    ACTIONS(48), 2,
      sym_regex,
      sym_quoted_name,
    STATE(35), 3,
      sym__hba_name,
      sym_role_group,
      sym_file_reference,
  [174] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_PLUS,
    ACTIONS(54), 1,
      anon_sym_AT,
    STATE(36), 1,
      sym_user,
    ACTIONS(50), 2,
      sym__word,
      aux_sym__hba_name_token1,
    ACTIONS(56), 2,
      sym_regex,
      sym_quoted_name,
    STATE(30), 3,
      sym__hba_name,
      sym_role_group,
      sym_file_reference,
  [200] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym__word,
    ACTIONS(60), 1,
      anon_sym_EQ,
    ACTIONS(62), 1,
      sym_string,
    ACTIONS(64), 1,
      aux_sym_number_token1,
    ACTIONS(66), 1,
      sym_boolean,
    ACTIONS(68), 2,
      sym_regex,
      sym_quoted_name,
    STATE(56), 2,
      sym__value,
      sym_number,
  [227] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_PLUS,
    ACTIONS(44), 1,
      anon_sym_AT,
    ACTIONS(40), 2,
      sym__word,
      aux_sym__hba_name_token1,
    ACTIONS(70), 2,
      sym_regex,
      sym_quoted_name,
    STATE(17), 3,
      sym__hba_name,
      sym_role_group,
      sym_file_reference,
  [250] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_PLUS,
    ACTIONS(54), 1,
      anon_sym_AT,
    ACTIONS(50), 2,
      sym__word,
      aux_sym__hba_name_token1,
    ACTIONS(72), 2,
      sym_regex,
      sym_quoted_name,
    STATE(34), 3,
      sym__hba_name,
      sym_role_group,
      sym_file_reference,
  [273] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    STATE(13), 1,
      aux_sym_database_repeat1,
    ACTIONS(74), 6,
      sym__word,
      aux_sym__hba_name_token1,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_regex,
      sym_quoted_name,
  [291] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    STATE(14), 1,
      aux_sym_database_repeat1,
    ACTIONS(78), 6,
      sym__word,
      aux_sym__hba_name_token1,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_regex,
      sym_quoted_name,
  [309] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_COMMA,
    STATE(14), 1,
      aux_sym_database_repeat1,
    ACTIONS(80), 6,
      sym__word,
      aux_sym__hba_name_token1,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_regex,
      sym_quoted_name,
  [327] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 7,
      sym__word,
      anon_sym_COMMA,
      aux_sym__hba_name_token1,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_regex,
      sym_quoted_name,
  [340] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 7,
      sym__word,
      anon_sym_COMMA,
      aux_sym__hba_name_token1,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_regex,
      sym_quoted_name,
  [353] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 7,
      sym__word,
      anon_sym_COMMA,
      aux_sym__hba_name_token1,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_regex,
      sym_quoted_name,
  [366] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 7,
      sym__word,
      anon_sym_COMMA,
      aux_sym__hba_name_token1,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_regex,
      sym_quoted_name,
  [379] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      aux_sym_number_token1,
    ACTIONS(91), 1,
      sym__word,
    ACTIONS(93), 2,
      sym_string,
      sym_boolean,
    STATE(55), 2,
      sym__value,
      sym_number,
  [397] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 2,
      ts_builtin_sym_end,
      sym__newline,
    ACTIONS(97), 2,
      sym__word,
      sym_string,
    ACTIONS(99), 2,
      sym_quoted_name,
      sym_backreference,
  [413] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 2,
      sym__word,
      sym_string,
    ACTIONS(99), 2,
      sym_quoted_name,
      sym_backreference,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      sym__newline,
  [429] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      sym__word,
    STATE(22), 1,
      aux_sym_hba_rule_repeat1,
    STATE(40), 1,
      sym_auth_option,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      sym__newline,
  [446] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      sym__word,
    STATE(28), 1,
      aux_sym_hba_rule_repeat1,
    STATE(40), 1,
      sym_auth_option,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      sym__newline,
  [463] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      sym__word,
    STATE(25), 1,
      aux_sym_hba_rule_repeat1,
    STATE(40), 1,
      sym_auth_option,
    ACTIONS(112), 2,
      ts_builtin_sym_end,
      sym__newline,
  [480] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      sym__word,
    STATE(22), 1,
      aux_sym_hba_rule_repeat1,
    STATE(40), 1,
      sym_auth_option,
    ACTIONS(114), 2,
      ts_builtin_sym_end,
      sym__newline,
  [497] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      sym__word,
    STATE(22), 1,
      aux_sym_hba_rule_repeat1,
    STATE(40), 1,
      sym_auth_option,
    ACTIONS(116), 2,
      ts_builtin_sym_end,
      sym__newline,
  [514] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      sym__word,
    STATE(26), 1,
      aux_sym_hba_rule_repeat1,
    STATE(40), 1,
      sym_auth_option,
    ACTIONS(118), 2,
      ts_builtin_sym_end,
      sym__newline,
  [531] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      sym__word,
    STATE(22), 1,
      aux_sym_hba_rule_repeat1,
    STATE(40), 1,
      sym_auth_option,
    ACTIONS(120), 2,
      ts_builtin_sym_end,
      sym__newline,
  [548] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      sym_ip_address,
    ACTIONS(122), 1,
      sym__word,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    STATE(29), 1,
      aux_sym_database_repeat1,
  [564] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      sym__word,
    ACTIONS(129), 1,
      anon_sym_COMMA,
    ACTIONS(131), 1,
      sym_ip_address,
    STATE(32), 1,
      aux_sym_database_repeat1,
  [580] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 2,
      sym__word,
      sym_string,
    ACTIONS(135), 2,
      sym_quoted_name,
      sym_backreference,
  [592] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_COMMA,
    ACTIONS(137), 1,
      sym__word,
    ACTIONS(139), 1,
      sym_ip_address,
    STATE(29), 1,
      aux_sym_database_repeat1,
  [608] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      aux_sym_number_token2,
    ACTIONS(141), 2,
      ts_builtin_sym_end,
      sym__newline,
  [619] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      sym__word,
    ACTIONS(80), 2,
      anon_sym_COMMA,
      sym_ip_address,
  [630] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    ACTIONS(131), 1,
      sym__word,
    STATE(38), 1,
      aux_sym_database_repeat1,
  [643] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      sym__word,
    ACTIONS(147), 1,
      sym_ip_address,
    STATE(39), 1,
      sym_address,
  [656] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 3,
      ts_builtin_sym_end,
      sym__newline,
      sym__word,
  [665] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    ACTIONS(139), 1,
      sym__word,
    STATE(14), 1,
      aux_sym_database_repeat1,
  [678] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      sym__word,
    ACTIONS(153), 1,
      sym_ip_address,
    STATE(23), 1,
      sym_auth_method,
  [691] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 3,
      ts_builtin_sym_end,
      sym__newline,
      sym__word,
  [700] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_EQ,
    ACTIONS(159), 2,
      sym_string,
      aux_sym_include_token1,
  [711] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 3,
      ts_builtin_sym_end,
      sym__newline,
      sym__word,
  [720] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym__word,
    ACTIONS(85), 2,
      anon_sym_COMMA,
      sym_ip_address,
  [731] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      sym__word,
    ACTIONS(87), 2,
      anon_sym_COMMA,
      sym_ip_address,
  [742] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      sym__word,
    ACTIONS(89), 2,
      anon_sym_COMMA,
      sym_ip_address,
  [753] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
    ACTIONS(171), 1,
      sym__newline,
  [763] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      sym__newline,
  [771] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      sym__word,
    ACTIONS(177), 1,
      sym_ip_address,
  [781] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      sym__word,
    STATE(24), 1,
      sym_auth_method,
  [791] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      sym__word,
    STATE(27), 1,
      sym_auth_method,
  [801] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 2,
      sym_quoted_name,
      aux_sym_auth_option_token1,
  [809] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 2,
      ts_builtin_sym_end,
      sym__newline,
  [817] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 2,
      ts_builtin_sym_end,
      sym__newline,
  [825] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 2,
      ts_builtin_sym_end,
      sym__newline,
  [833] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 2,
      ts_builtin_sym_end,
      sym__newline,
  [841] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 2,
      ts_builtin_sym_end,
      sym__newline,
  [849] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 2,
      ts_builtin_sym_end,
      sym__newline,
  [857] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 2,
      ts_builtin_sym_end,
      sym__newline,
  [865] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym__word,
    ACTIONS(197), 1,
      sym_ip_address,
  [875] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(171), 1,
      sym__newline,
  [885] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 2,
      ts_builtin_sym_end,
      sym__newline,
  [893] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 2,
      ts_builtin_sym_end,
      sym__newline,
  [901] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 2,
      sym_string,
      aux_sym_include_token1,
  [909] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_EQ,
  [916] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      sym__newline,
  [923] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
  [930] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      sym__word,
  [937] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      aux_sym_file_reference_token1,
  [944] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      sym__word,
  [951] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      aux_sym_file_reference_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 76,
  [SMALL_STATE(5)] = 96,
  [SMALL_STATE(6)] = 122,
  [SMALL_STATE(7)] = 148,
  [SMALL_STATE(8)] = 174,
  [SMALL_STATE(9)] = 200,
  [SMALL_STATE(10)] = 227,
  [SMALL_STATE(11)] = 250,
  [SMALL_STATE(12)] = 273,
  [SMALL_STATE(13)] = 291,
  [SMALL_STATE(14)] = 309,
  [SMALL_STATE(15)] = 327,
  [SMALL_STATE(16)] = 340,
  [SMALL_STATE(17)] = 353,
  [SMALL_STATE(18)] = 366,
  [SMALL_STATE(19)] = 379,
  [SMALL_STATE(20)] = 397,
  [SMALL_STATE(21)] = 413,
  [SMALL_STATE(22)] = 429,
  [SMALL_STATE(23)] = 446,
  [SMALL_STATE(24)] = 463,
  [SMALL_STATE(25)] = 480,
  [SMALL_STATE(26)] = 497,
  [SMALL_STATE(27)] = 514,
  [SMALL_STATE(28)] = 531,
  [SMALL_STATE(29)] = 548,
  [SMALL_STATE(30)] = 564,
  [SMALL_STATE(31)] = 580,
  [SMALL_STATE(32)] = 592,
  [SMALL_STATE(33)] = 608,
  [SMALL_STATE(34)] = 619,
  [SMALL_STATE(35)] = 630,
  [SMALL_STATE(36)] = 643,
  [SMALL_STATE(37)] = 656,
  [SMALL_STATE(38)] = 665,
  [SMALL_STATE(39)] = 678,
  [SMALL_STATE(40)] = 691,
  [SMALL_STATE(41)] = 700,
  [SMALL_STATE(42)] = 711,
  [SMALL_STATE(43)] = 720,
  [SMALL_STATE(44)] = 731,
  [SMALL_STATE(45)] = 742,
  [SMALL_STATE(46)] = 753,
  [SMALL_STATE(47)] = 763,
  [SMALL_STATE(48)] = 771,
  [SMALL_STATE(49)] = 781,
  [SMALL_STATE(50)] = 791,
  [SMALL_STATE(51)] = 801,
  [SMALL_STATE(52)] = 809,
  [SMALL_STATE(53)] = 817,
  [SMALL_STATE(54)] = 825,
  [SMALL_STATE(55)] = 833,
  [SMALL_STATE(56)] = 841,
  [SMALL_STATE(57)] = 849,
  [SMALL_STATE(58)] = 857,
  [SMALL_STATE(59)] = 865,
  [SMALL_STATE(60)] = 875,
  [SMALL_STATE(61)] = 885,
  [SMALL_STATE(62)] = 893,
  [SMALL_STATE(63)] = 901,
  [SMALL_STATE(64)] = 909,
  [SMALL_STATE(65)] = 916,
  [SMALL_STATE(66)] = 923,
  [SMALL_STATE(67)] = 930,
  [SMALL_STATE(68)] = 937,
  [SMALL_STATE(69)] = 944,
  [SMALL_STATE(70)] = 951,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_database, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_database, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_database_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_database_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hba_name, 1, 0, 4),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_role_group, 2, 0, 11),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_reference, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_hba_rule_repeat1, 2, 0, 17),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_hba_rule_repeat1, 2, 0, 17), SHIFT_REPEAT(64),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hba_rule, 5, 0, 16),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hba_rule, 4, 0, 12),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hba_rule, 5, 0, 15),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hba_rule, 7, 0, 21),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hba_rule, 6, 0, 18),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hba_rule, 6, 0, 19),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_database_repeat1, 2, 0, 0),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_database_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_user, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_user, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_auth_method, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_hba_rule_repeat1, 1, 0, 14),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_auth_option, 3, 0, 20),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__hba_name, 1, 0, 4),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_role_group, 2, 0, 11),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_reference, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 2, 0, 3),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_address, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_address, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user_mapping, 3, 0, 5),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user_mapping, 3, 0, 6),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 3, 0, 7),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 2, 0, 2),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user_mapping, 3, 0, 8),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_address, 1, 0, 13),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_address, 1, 0, 13),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user_mapping, 3, 0, 9),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 3, 0, 10),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [207] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_postgresql_conf(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__word,
    .primary_state_ids = ts_primary_state_ids,
    .name = "postgresql_conf",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
