/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 70
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 9
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 22
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__word = 1,
  sym__newline = 2,
  sym_comment = 3,
  anon_sym_EQ = 4,
  sym_string = 5,
  aux_sym_number_token1 = 6,
  aux_sym_number_token2 = 7,
  sym_boolean = 8,
  anon_sym_include = 9,
  anon_sym_include_if_exists = 10,
  anon_sym_include_dir = 11,
  aux_sym_include_token1 = 12,
  anon_sym_local = 13,
  anon_sym_host = 14,
  anon_sym_hostssl = 15,
  anon_sym_hostnossl = 16,
  anon_sym_hostgssenc = 17,
  anon_sym_hostnogssenc = 18,
  anon_sym_COMMA = 19,
  anon_sym_PLUS = 20,
  anon_sym_AT = 21,
  aux_sym_file_reference_token1 = 22,
  sym_regex = 23,
  sym_quoted_name = 24,
  sym_ip_address = 25,
  aux_sym_auth_option_token1 = 26,
  sym_backreference = 27,
  sym_source_file = 28,
  sym__entry = 29,
  sym_setting = 30,
  sym__value = 31,
  sym_number = 32,
  sym_include = 33,
  sym_hba_rule = 34,
  sym_database = 35,
  sym_user = 36,
  sym__hba_name = 37,
  sym_role_group = 38,
  sym_file_reference = 39,
  sym_address = 40,
  sym_auth_method = 41,
  sym_auth_option = 42,
  sym_user_mapping = 43,
  aux_sym_source_file_repeat1 = 44,
  aux_sym_hba_rule_repeat1 = 45,
  aux_sym_database_repeat1 = 46,
  alias_sym_bare_value = 47,
  alias_sym_database_user = 48,
  alias_sym_hostname = 49,
  alias_sym_map_name = 50,
  alias_sym_name = 51,
  alias_sym_netmask = 52,
  alias_sym_option_name = 53,
  alias_sym_setting_name = 54,
  alias_sym_system_user = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__word] = "_word",
  [sym__newline] = "_newline",
  [sym_comment] = "comment",
  [anon_sym_EQ] = "=",
  [sym_string] = "string",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "unit",
  [sym_boolean] = "boolean",
  [anon_sym_include] = "include",
  [anon_sym_include_if_exists] = "include_if_exists",
  [anon_sym_include_dir] = "include_dir",
  [aux_sym_include_token1] = "path",
  [anon_sym_local] = "connection_type",
  [anon_sym_host] = "connection_type",
  [anon_sym_hostssl] = "connection_type",
  [anon_sym_hostnossl] = "connection_type",
  [anon_sym_hostgssenc] = "connection_type",
  [anon_sym_hostnogssenc] = "connection_type",
  [anon_sym_COMMA] = ",",
  [anon_sym_PLUS] = "+",
  [anon_sym_AT] = "@",
  [aux_sym_file_reference_token1] = "path",
  [sym_regex] = "regex",
  [sym_quoted_name] = "quoted_name",
  [sym_ip_address] = "ip_address",
  [aux_sym_auth_option_token1] = "option_value",
  [sym_backreference] = "backreference",
  [sym_source_file] = "source_file",
  [sym__entry] = "_entry",
  [sym_setting] = "setting",
  [sym__value] = "_value",
  [sym_number] = "number",
  [sym_include] = "include",
  [sym_hba_rule] = "hba_rule",
  [sym_database] = "database",
  [sym_user] = "user",
  [sym__hba_name] = "_hba_name",
  [sym_role_group] = "role_group",
  [sym_file_reference] = "file_reference",
  [sym_address] = "address",
  [sym_auth_method] = "auth_method",
  [sym_auth_option] = "auth_option",
  [sym_user_mapping] = "user_mapping",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_hba_rule_repeat1] = "hba_rule_repeat1",
  [aux_sym_database_repeat1] = "database_repeat1",
  [alias_sym_bare_value] = "bare_value",
  [alias_sym_database_user] = "database_user",
  [alias_sym_hostname] = "hostname",
  [alias_sym_map_name] = "map_name",
  [alias_sym_name] = "name",
  [alias_sym_netmask] = "netmask",
  [alias_sym_option_name] = "option_name",
  [alias_sym_setting_name] = "setting_name",
  [alias_sym_system_user] = "system_user",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__word] = sym__word,
  [sym__newline] = sym__newline,
  [sym_comment] = sym_comment,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_string] = sym_string,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [sym_boolean] = sym_boolean,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_include_if_exists] = anon_sym_include_if_exists,
  [anon_sym_include_dir] = anon_sym_include_dir,
  [aux_sym_include_token1] = aux_sym_include_token1,
  [anon_sym_local] = anon_sym_local,
  [anon_sym_host] = anon_sym_local,
  [anon_sym_hostssl] = anon_sym_local,
  [anon_sym_hostnossl] = anon_sym_local,
  [anon_sym_hostgssenc] = anon_sym_local,
  [anon_sym_hostnogssenc] = anon_sym_local,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_file_reference_token1] = aux_sym_include_token1,
  [sym_regex] = sym_regex,
  [sym_quoted_name] = sym_quoted_name,
  [sym_ip_address] = sym_ip_address,
  [aux_sym_auth_option_token1] = aux_sym_auth_option_token1,
  [sym_backreference] = sym_backreference,
  [sym_source_file] = sym_source_file,
  [sym__entry] = sym__entry,
  [sym_setting] = sym_setting,
  [sym__value] = sym__value,
  [sym_number] = sym_number,
  [sym_include] = sym_include,
  [sym_hba_rule] = sym_hba_rule,
  [sym_database] = sym_database,
  [sym_user] = sym_user,
  [sym__hba_name] = sym__hba_name,
  [sym_role_group] = sym_role_group,
  [sym_file_reference] = sym_file_reference,
  [sym_address] = sym_address,
  [sym_auth_method] = sym_auth_method,
  [sym_auth_option] = sym_auth_option,
  [sym_user_mapping] = sym_user_mapping,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_hba_rule_repeat1] = aux_sym_hba_rule_repeat1,
  [aux_sym_database_repeat1] = aux_sym_database_repeat1,
  [alias_sym_bare_value] = alias_sym_bare_value,
  [alias_sym_database_user] = alias_sym_database_user,
  [alias_sym_hostname] = alias_sym_hostname,
  [alias_sym_map_name] = alias_sym_map_name,
  [alias_sym_name] = alias_sym_name,
  [alias_sym_netmask] = alias_sym_netmask,
  [alias_sym_option_name] = alias_sym_option_name,
  [alias_sym_setting_name] = alias_sym_setting_name,
  [alias_sym_system_user] = alias_sym_system_user,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__word] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_include_if_exists] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_include_dir] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_include_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_local] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_host] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_hostssl] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_hostnossl] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_hostgssenc] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_hostnogssenc] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_file_reference_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_regex] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_name] = {
    .visible = true,
    .named = true,
  },
  [sym_ip_address] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_auth_option_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_backreference] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__entry] = {
    .visible = false,
    .named = true,
  },
  [sym_setting] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_include] = {
    .visible = true,
    .named = true,
  },
  [sym_hba_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_database] = {
    .visible = true,
    .named = true,
  },
  [sym_user] = {
    .visible = true,
    .named = true,
  },
  [sym__hba_name] = {
    .visible = false,
    .named = true,
  },
  [sym_role_group] = {
    .visible = true,
    .named = true,
  },
  [sym_file_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_address] = {
    .visible = true,
    .named = true,
  },
  [sym_auth_method] = {
    .visible = true,
    .named = true,
  },
  [sym_auth_option] = {
    .visible = true,
    .named = true,
  },
  [sym_user_mapping] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_hba_rule_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_database_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_bare_value] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_database_user] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_hostname] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_map_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_netmask] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_option_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_setting_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_system_user] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_address = 1,
  field_database = 2,
  field_database_user = 3,
  field_map = 4,
  field_method = 5,
  field_name = 6,
  field_netmask = 7,
  field_option = 8,
  field_path = 9,
  field_system_user = 10,
  field_type = 11,
  field_user = 12,
  field_value = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_address] = "address",
  [field_database] = "database",
  [field_database_user] = "database_user",
  [field_map] = "map",
  [field_method] = "method",
  [field_name] = "name",
  [field_netmask] = "netmask",
  [field_option] = "option",
  [field_path] = "path",
  [field_system_user] = "system_user",
  [field_type] = "type",
  [field_user] = "user",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 2},
  [3] = {.index = 2, .length = 1},
  [5] = {.index = 3, .length = 3},
  [6] = {.index = 3, .length = 3},
  [7] = {.index = 6, .length = 2},
  [8] = {.index = 3, .length = 3},
  [9] = {.index = 3, .length = 3},
  [10] = {.index = 8, .length = 1},
  [12] = {.index = 9, .length = 4},
  [14] = {.index = 13, .length = 1},
  [15] = {.index = 14, .length = 5},
  [16] = {.index = 19, .length = 5},
  [17] = {.index = 24, .length = 2},
  [18] = {.index = 26, .length = 6},
  [19] = {.index = 32, .length = 6},
  [20] = {.index = 6, .length = 2},
  [21] = {.index = 38, .length = 7},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_value, 1},
  [2] =
    {field_path, 1},
  [3] =
    {field_database_user, 2},
    {field_map, 0},
    {field_system_user, 1},
  [6] =
    {field_name, 0},
    {field_value, 2},
  [8] =
    {field_path, 2},
  [9] =
    {field_database, 1},
    {field_method, 3},
    {field_type, 0},
    {field_user, 2},
  [13] =
    {field_option, 0},
  [14] =
    {field_database, 1},
    {field_method, 3},
    {field_option, 4, .inherited = true},
    {field_type, 0},
    {field_user, 2},
  [19] =
    {field_address, 3},
    {field_database, 1},
    {field_method, 4},
    {field_type, 0},
    {field_user, 2},
  [24] =
    {field_option, 0, .inherited = true},
    {field_option, 1, .inherited = true},
  [26] =
    {field_address, 3},
    {field_database, 1},
    {field_method, 5},
    {field_netmask, 4},
    {field_type, 0},
    {field_user, 2},
  [32] =
    {field_address, 3},
    {field_database, 1},
    {field_method, 4},
    {field_option, 5, .inherited = true},
    {field_type, 0},
    {field_user, 2},
  [38] =
    {field_address, 3},
    {field_database, 1},
    {field_method, 5},
    {field_netmask, 4},
    {field_option, 6, .inherited = true},
    {field_type, 0},
    {field_user, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_bare_value,
  },
  [2] = {
    [0] = alias_sym_setting_name,
  },
  [4] = {
    [0] = alias_sym_name,
  },
  [5] = {
    [0] = alias_sym_map_name,
    [1] = alias_sym_system_user,
    [2] = alias_sym_database_user,
  },
  [6] = {
    [0] = alias_sym_map_name,
    [1] = alias_sym_system_user,
  },
  [7] = {
    [0] = alias_sym_setting_name,
  },
  [8] = {
    [0] = alias_sym_map_name,
    [2] = alias_sym_database_user,
  },
  [9] = {
    [0] = alias_sym_map_name,
  },
  [11] = {
    [1] = alias_sym_name,
  },
  [13] = {
    [0] = alias_sym_hostname,
  },
  [18] = {
    [4] = alias_sym_netmask,
  },
  [20] = {
    [0] = alias_sym_option_name,
  },
  [21] = {
    [4] = alias_sym_netmask,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 14,
  [30] = 30,
  [31] = 28,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 30,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 15,
  [42] = 17,
  [43] = 18,
  [44] = 19,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 63,
  [69] = 67,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '\n', 31,
        '\r', 1,
        '"', 3,
        '#', 32,
        '\'', 8,
        '+', 44,
        ',', 43,
        '-', 20,
        '/', 47,
        '=', 36,
        '@', 45,
        '\\', 21,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(31);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(57);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == '\'') ADVANCE(8);
      if (lookahead == '=') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(42);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == ',') ADVANCE(43);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(6);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ',') ADVANCE(46);
      END_STATE();
    case 8:
      if (lookahead == '\'') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(25);
      if (lookahead == ':') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == '.') ADVANCE(25);
      if (lookahead == ':') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == '.') ADVANCE(25);
      if (lookahead == ':') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == '.') ADVANCE(26);
      END_STATE();
    case 13:
      if (lookahead == '.') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == '.') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == '.') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == '.') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == '.') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == ':') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 19:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 28:
      if (eof) ADVANCE(30);
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(28);
      END_STATE();
    case 29:
      if (eof) ADVANCE(30);
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == ':') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != ',' &&
          lookahead != '=') ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__word);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != ',' &&
          lookahead != '=') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__word);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != ',' &&
          lookahead != '=') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '\'') ADVANCE(8);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_include_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_file_reference_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ',') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_regex);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ',') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_quoted_name);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_ip_address);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_ip_address);
      if (lookahead == '/') ADVANCE(34);
      if (('.' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_ip_address);
      if (lookahead == '/') ADVANCE(24);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_ip_address);
      if (lookahead == '/') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_ip_address);
      if (lookahead == '/') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_ip_address);
      if (lookahead == '/') ADVANCE(24);
      if (('.' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_ip_address);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_ip_address);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_auth_option_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_backreference);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'h') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(2);
      if (lookahead == 'l') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(4);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(5);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(6);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(7);
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 6:
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(14);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 8:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_boolean);
      END_STATE();
    case 14:
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(13);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 20:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_host);
      if (lookahead == 'g') ADVANCE(26);
      if (lookahead == 'n') ADVANCE(27);
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 25:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 29:
      if (lookahead == 'd') ADVANCE(34);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_local);
      END_STATE();
    case 31:
      if (lookahead == 's') ADVANCE(35);
      END_STATE();
    case 32:
      if (lookahead == 'g') ADVANCE(36);
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(38);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 36:
      if (lookahead == 's') ADVANCE(41);
      END_STATE();
    case 37:
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_hostssl);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_include);
      if (lookahead == '_') ADVANCE(43);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 41:
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 42:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 43:
      if (lookahead == 'd') ADVANCE(47);
      if (lookahead == 'i') ADVANCE(48);
      END_STATE();
    case 44:
      if (lookahead == 'c') ADVANCE(49);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_hostnossl);
      END_STATE();
    case 47:
      if (lookahead == 'i') ADVANCE(51);
      END_STATE();
    case 48:
      if (lookahead == 'f') ADVANCE(52);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_hostgssenc);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(53);
      END_STATE();
    case 51:
      if (lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 52:
      if (lookahead == '_') ADVANCE(55);
      END_STATE();
    case 53:
      if (lookahead == 'c') ADVANCE(56);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_include_dir);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_hostnogssenc);
      END_STATE();
    case 57:
      if (lookahead == 'x') ADVANCE(58);
      END_STATE();
    case 58:
      if (lookahead == 'i') ADVANCE(59);
      END_STATE();
    case 59:
      if (lookahead == 's') ADVANCE(60);
      END_STATE();
    case 60:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 61:
      if (lookahead == 's') ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_include_if_exists);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 29},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 5},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 7},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__word] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_include_if_exists] = ACTIONS(1),
    [anon_sym_include_dir] = ACTIONS(1),
    [anon_sym_local] = ACTIONS(1),
    [anon_sym_host] = ACTIONS(1),
    [anon_sym_hostssl] = ACTIONS(1),
    [anon_sym_hostnossl] = ACTIONS(1),
    [anon_sym_hostgssenc] = ACTIONS(1),
    [anon_sym_hostnogssenc] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_regex] = ACTIONS(1),
    [sym_quoted_name] = ACTIONS(1),
    [sym_backreference] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(66),
    [sym__entry] = STATE(59),
    [sym_setting] = STATE(59),
    [sym_include] = STATE(59),
    [sym_hba_rule] = STATE(59),
    [sym_user_mapping] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym__word] = ACTIONS(7),
    [sym__newline] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_include] = ACTIONS(11),
    [anon_sym_include_if_exists] = ACTIONS(11),
    [anon_sym_include_dir] = ACTIONS(11),
    [anon_sym_local] = ACTIONS(13),
    [anon_sym_host] = ACTIONS(15),
    [anon_sym_hostssl] = ACTIONS(15),
    [anon_sym_hostnossl] = ACTIONS(15),
    [anon_sym_hostgssenc] = ACTIONS(15),
    [anon_sym_hostnogssenc] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym__word,
    ACTIONS(22), 1,
      sym__newline,
    ACTIONS(28), 1,
      anon_sym_local,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(25), 3,
      anon_sym_include,
      anon_sym_include_if_exists,
      anon_sym_include_dir,
    ACTIONS(31), 5,
      anon_sym_host,
      anon_sym_hostssl,
      anon_sym_hostnossl,
      anon_sym_hostgssenc,
      anon_sym_hostnogssenc,
    STATE(65), 5,
      sym__entry,
      sym_setting,
      sym_include,
      sym_hba_rule,
      sym_user_mapping,
  [38] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__word,
    ACTIONS(13), 1,
      anon_sym_local,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(36), 1,
      sym__newline,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(11), 3,
      anon_sym_include,
      anon_sym_include_if_exists,
      anon_sym_include_dir,
    ACTIONS(15), 5,
      anon_sym_host,
      anon_sym_hostssl,
      anon_sym_hostnossl,
      anon_sym_hostgssenc,
      anon_sym_hostnogssenc,
    STATE(53), 5,
      sym__entry,
      sym_setting,
      sym_include,
      sym_hba_rule,
      sym_user_mapping,
  [76] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 2,
      ts_builtin_sym_end,
      sym__newline,
    ACTIONS(38), 10,
      sym__word,
      anon_sym_include,
      anon_sym_include_if_exists,
      anon_sym_include_dir,
      anon_sym_local,
      anon_sym_host,
      anon_sym_hostssl,
      anon_sym_hostnossl,
      anon_sym_hostgssenc,
      anon_sym_hostnogssenc,
  [96] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      sym__word,
    ACTIONS(42), 1,
      anon_sym_EQ,
    ACTIONS(46), 1,
      aux_sym_number_token1,
    ACTIONS(44), 2,
      sym_string,
      sym_boolean,
    ACTIONS(48), 2,
      sym_regex,
      sym_quoted_name,
    STATE(54), 2,
      sym__value,
      sym_number,
  [121] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym__word,
    ACTIONS(52), 1,
      anon_sym_PLUS,
    ACTIONS(54), 1,
      anon_sym_AT,
    STATE(7), 1,
      sym_database,
    ACTIONS(56), 2,
      sym_regex,
      sym_quoted_name,
    STATE(12), 3,
      sym__hba_name,
      sym_role_group,
      sym_file_reference,
  [146] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym__word,
    ACTIONS(52), 1,
      anon_sym_PLUS,
    ACTIONS(54), 1,
      anon_sym_AT,
    STATE(58), 1,
      sym_user,
    ACTIONS(58), 2,
      sym_regex,
      sym_quoted_name,
    STATE(31), 3,
      sym__hba_name,
      sym_role_group,
      sym_file_reference,
  [171] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      sym__word,
    ACTIONS(62), 1,
      anon_sym_PLUS,
    ACTIONS(64), 1,
      anon_sym_AT,
    STATE(33), 1,
      sym_user,
    ACTIONS(66), 2,
      sym_regex,
      sym_quoted_name,
    STATE(28), 3,
      sym__hba_name,
      sym_role_group,
      sym_file_reference,
  [196] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym__word,
    ACTIONS(52), 1,
      anon_sym_PLUS,
    ACTIONS(54), 1,
      anon_sym_AT,
    STATE(8), 1,
      sym_database,
    ACTIONS(56), 2,
      sym_regex,
      sym_quoted_name,
    STATE(12), 3,
      sym__hba_name,
      sym_role_group,
      sym_file_reference,
  [221] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym__word,
    ACTIONS(52), 1,
      anon_sym_PLUS,
    ACTIONS(54), 1,
      anon_sym_AT,
    ACTIONS(68), 2,
      sym_regex,
      sym_quoted_name,
    STATE(19), 3,
      sym__hba_name,
      sym_role_group,
      sym_file_reference,
  [243] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      sym__word,
    ACTIONS(62), 1,
      anon_sym_PLUS,
    ACTIONS(64), 1,
      anon_sym_AT,
    ACTIONS(70), 2,
      sym_regex,
      sym_quoted_name,
    STATE(44), 3,
      sym__hba_name,
      sym_role_group,
      sym_file_reference,
  [265] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    STATE(13), 1,
      aux_sym_database_repeat1,
    ACTIONS(72), 5,
      sym__word,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_regex,
      sym_quoted_name,
  [282] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    STATE(14), 1,
      aux_sym_database_repeat1,
    ACTIONS(76), 5,
      sym__word,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_regex,
      sym_quoted_name,
  [299] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_COMMA,
    STATE(14), 1,
      aux_sym_database_repeat1,
    ACTIONS(78), 5,
      sym__word,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_regex,
      sym_quoted_name,
  [316] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 6,
      sym__word,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_regex,
      sym_quoted_name,
  [328] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      aux_sym_number_token1,
    ACTIONS(85), 1,
      sym__word,
    ACTIONS(87), 2,
      sym_string,
      sym_boolean,
    STATE(61), 2,
      sym__value,
      sym_number,
  [346] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 6,
      sym__word,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_regex,
      sym_quoted_name,
  [358] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 6,
      sym__word,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_regex,
      sym_quoted_name,
  [370] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 6,
      sym__word,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_regex,
      sym_quoted_name,
  [382] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym__word,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      sym__newline,
    ACTIONS(97), 2,
      sym_quoted_name,
      sym_backreference,
  [397] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      sym__word,
    STATE(26), 1,
      aux_sym_hba_rule_repeat1,
    STATE(37), 1,
      sym_auth_option,
    ACTIONS(99), 2,
      ts_builtin_sym_end,
      sym__newline,
  [414] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      sym__word,
    STATE(25), 1,
      aux_sym_hba_rule_repeat1,
    STATE(37), 1,
      sym_auth_option,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      sym__newline,
  [431] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      sym__word,
    STATE(21), 1,
      aux_sym_hba_rule_repeat1,
    STATE(37), 1,
      sym_auth_option,
    ACTIONS(105), 2,
      ts_builtin_sym_end,
      sym__newline,
  [448] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      sym__word,
    STATE(27), 1,
      aux_sym_hba_rule_repeat1,
    STATE(37), 1,
      sym_auth_option,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      sym__newline,
  [465] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      sym__word,
    STATE(26), 1,
      aux_sym_hba_rule_repeat1,
    STATE(37), 1,
      sym_auth_option,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      sym__newline,
  [482] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      sym__word,
    STATE(26), 1,
      aux_sym_hba_rule_repeat1,
    STATE(37), 1,
      sym_auth_option,
    ACTIONS(111), 2,
      ts_builtin_sym_end,
      sym__newline,
  [499] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      sym__word,
    STATE(26), 1,
      aux_sym_hba_rule_repeat1,
    STATE(37), 1,
      sym_auth_option,
    ACTIONS(116), 2,
      ts_builtin_sym_end,
      sym__newline,
  [516] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      sym__word,
    ACTIONS(120), 1,
      anon_sym_COMMA,
    ACTIONS(122), 1,
      sym_ip_address,
    STATE(30), 1,
      aux_sym_database_repeat1,
  [532] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      sym_ip_address,
    ACTIONS(124), 1,
      sym__word,
    ACTIONS(126), 1,
      anon_sym_COMMA,
    STATE(29), 1,
      aux_sym_database_repeat1,
  [548] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_COMMA,
    ACTIONS(129), 1,
      sym__word,
    ACTIONS(131), 1,
      sym_ip_address,
    STATE(29), 1,
      aux_sym_database_repeat1,
  [564] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    ACTIONS(122), 1,
      sym__word,
    STATE(35), 1,
      aux_sym_database_repeat1,
  [577] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_EQ,
    ACTIONS(135), 2,
      sym_string,
      aux_sym_include_token1,
  [588] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym__word,
    ACTIONS(139), 1,
      sym_ip_address,
    STATE(36), 1,
      sym_address,
  [601] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 3,
      ts_builtin_sym_end,
      sym__newline,
      sym__word,
  [610] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    ACTIONS(131), 1,
      sym__word,
    STATE(14), 1,
      aux_sym_database_repeat1,
  [623] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym__word,
    ACTIONS(145), 1,
      sym_ip_address,
    STATE(22), 1,
      sym_auth_method,
  [636] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 3,
      ts_builtin_sym_end,
      sym__newline,
      sym__word,
  [645] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      aux_sym_number_token2,
    ACTIONS(149), 2,
      ts_builtin_sym_end,
      sym__newline,
  [656] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym__word,
    ACTIONS(155), 2,
      sym_quoted_name,
      sym_backreference,
  [667] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 3,
      ts_builtin_sym_end,
      sym__newline,
      sym__word,
  [676] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      sym__word,
    ACTIONS(83), 2,
      anon_sym_COMMA,
      sym_ip_address,
  [687] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      sym__word,
    ACTIONS(89), 2,
      anon_sym_COMMA,
      sym_ip_address,
  [698] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym__word,
    ACTIONS(91), 2,
      anon_sym_COMMA,
      sym_ip_address,
  [709] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      sym__word,
    ACTIONS(78), 2,
      anon_sym_COMMA,
      sym_ip_address,
  [720] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 2,
      ts_builtin_sym_end,
      sym__newline,
  [728] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 2,
      ts_builtin_sym_end,
      sym__newline,
  [736] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      sym__word,
    ACTIONS(171), 1,
      sym_ip_address,
  [746] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      sym__newline,
  [754] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 2,
      sym_quoted_name,
      aux_sym_auth_option_token1,
  [762] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 2,
      ts_builtin_sym_end,
      sym__newline,
  [770] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      sym__word,
    STATE(24), 1,
      sym_auth_method,
  [780] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 2,
      sym_string,
      aux_sym_include_token1,
  [788] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      ts_builtin_sym_end,
    ACTIONS(185), 1,
      sym__newline,
  [798] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 2,
      ts_builtin_sym_end,
      sym__newline,
  [806] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 2,
      ts_builtin_sym_end,
      sym__newline,
  [814] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 2,
      ts_builtin_sym_end,
      sym__newline,
  [822] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 2,
      ts_builtin_sym_end,
      sym__newline,
  [830] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      sym__word,
    STATE(23), 1,
      sym_auth_method,
  [840] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(185), 1,
      sym__newline,
  [850] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      sym__newline,
  [858] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 2,
      ts_builtin_sym_end,
      sym__newline,
  [866] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym__word,
    ACTIONS(199), 1,
      sym_ip_address,
  [876] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      sym__word,
  [883] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_EQ,
  [890] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym__newline,
  [897] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      ts_builtin_sym_end,
  [904] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      aux_sym_file_reference_token1,
  [911] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      sym__word,
  [918] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      aux_sym_file_reference_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 76,
  [SMALL_STATE(5)] = 96,
  [SMALL_STATE(6)] = 121,
  [SMALL_STATE(7)] = 146,
  [SMALL_STATE(8)] = 171,
  [SMALL_STATE(9)] = 196,
  [SMALL_STATE(10)] = 221,
  [SMALL_STATE(11)] = 243,
  [SMALL_STATE(12)] = 265,
  [SMALL_STATE(13)] = 282,
  [SMALL_STATE(14)] = 299,
  [SMALL_STATE(15)] = 316,
  [SMALL_STATE(16)] = 328,
  [SMALL_STATE(17)] = 346,
  [SMALL_STATE(18)] = 358,
  [SMALL_STATE(19)] = 370,
  [SMALL_STATE(20)] = 382,
  [SMALL_STATE(21)] = 397,
  [SMALL_STATE(22)] = 414,
  [SMALL_STATE(23)] = 431,
  [SMALL_STATE(24)] = 448,
  [SMALL_STATE(25)] = 465,
  [SMALL_STATE(26)] = 482,
  [SMALL_STATE(27)] = 499,
  [SMALL_STATE(28)] = 516,
  [SMALL_STATE(29)] = 532,
  [SMALL_STATE(30)] = 548,
  [SMALL_STATE(31)] = 564,
  [SMALL_STATE(32)] = 577,
  [SMALL_STATE(33)] = 588,
  [SMALL_STATE(34)] = 601,
  [SMALL_STATE(35)] = 610,
  [SMALL_STATE(36)] = 623,
  [SMALL_STATE(37)] = 636,
  [SMALL_STATE(38)] = 645,
  [SMALL_STATE(39)] = 656,
  [SMALL_STATE(40)] = 667,
  [SMALL_STATE(41)] = 676,
  [SMALL_STATE(42)] = 687,
  [SMALL_STATE(43)] = 698,
  [SMALL_STATE(44)] = 709,
  [SMALL_STATE(45)] = 720,
  [SMALL_STATE(46)] = 728,
  [SMALL_STATE(47)] = 736,
  [SMALL_STATE(48)] = 746,
  [SMALL_STATE(49)] = 754,
  [SMALL_STATE(50)] = 762,
  [SMALL_STATE(51)] = 770,
  [SMALL_STATE(52)] = 780,
  [SMALL_STATE(53)] = 788,
  [SMALL_STATE(54)] = 798,
  [SMALL_STATE(55)] = 806,
  [SMALL_STATE(56)] = 814,
  [SMALL_STATE(57)] = 822,
  [SMALL_STATE(58)] = 830,
  [SMALL_STATE(59)] = 840,
  [SMALL_STATE(60)] = 850,
  [SMALL_STATE(61)] = 858,
  [SMALL_STATE(62)] = 866,
  [SMALL_STATE(63)] = 876,
  [SMALL_STATE(64)] = 883,
  [SMALL_STATE(65)] = 890,
  [SMALL_STATE(66)] = 897,
  [SMALL_STATE(67)] = 904,
  [SMALL_STATE(68)] = 911,
  [SMALL_STATE(69)] = 918,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_database, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_database, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_database_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_database_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hba_name, 1, 0, 4),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_role_group, 2, 0, 11),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_reference, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 1),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hba_rule, 5, 0, 15),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hba_rule, 5, 0, 16),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hba_rule, 4, 0, 12),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hba_rule, 6, 0, 18),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hba_rule, 6, 0, 19),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_hba_rule_repeat1, 2, 0, 17),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_hba_rule_repeat1, 2, 0, 17), SHIFT_REPEAT(64),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hba_rule, 7, 0, 21),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_user, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_database_repeat1, 2, 0, 0),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_database_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_user, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_auth_method, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_hba_rule_repeat1, 1, 0, 14),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_auth_option, 3, 0, 20),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__hba_name, 1, 0, 4),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_role_group, 2, 0, 11),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_reference, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user_mapping, 3, 0, 8),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_address, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_address, 1, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user_mapping, 3, 0, 9),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 3, 0, 10),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 2, 0, 2),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user_mapping, 3, 0, 5),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 2, 0, 3),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user_mapping, 3, 0, 6),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 3, 0, 7),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_address, 1, 0, 13),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_address, 1, 0, 13),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [205] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_postgresql_conf(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__word,
    .primary_state_ids = ts_primary_state_ids,
    .name = "postgresql_conf",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
